### ISSUE TITLE
cannot install this package

### ISSUE THREAD

**Issue by pbiecek** [sambaala/linkspotter#1]
The 
```
devtools::install_github("sambaala/linkspotter")
```
returns
```
Error: Line starting 'Several and differen ...' is malformed!
```
something is wrong with the DESCRIPTION file

**Comment by sambaala** [comment]
I corrected DESCRIPTION and NAMESPACE files. It now works. Please tell me if it is okay on your side.

**Comment by pbiecek** [comment]
Yes, now it's working, thanks
